#!/usr/bin/env python3
"""Generate the autonomy matrix from the live merge policy (Factory#1962).

Every row is produced by CALLING ``merge.merge_policy`` / ``review_tier``;
nothing is transcribed, so the page cannot drift from the code.

Usage:
    python scripts/gen_autonomy_matrix.py            # write the outputs
    python scripts/gen_autonomy_matrix.py --stdout   # print the markdown
    python scripts/gen_autonomy_matrix.py --check    # fail if outputs are stale
"""

from __future__ import annotations

import argparse
import ast
import contextlib
import functools
import inspect
import itertools
import json
import os
import sys
import tempfile
import tomllib
from collections.abc import Collection, Iterator
from pathlib import Path
from types import ModuleType
from typing import cast

_REPO_ROOT = Path(__file__).resolve().parents[1]
for _p in (_REPO_ROOT / "apps" / "backend", _REPO_ROOT / "apps" / "web-server"):
    sys.path.insert(0, str(_p))

_GENERATED_BANNER = (
    "GENERATED by scripts/gen_autonomy_matrix.py from merge.merge_policy.\n"
    "DO NOT EDIT BY HAND - rerun the generator (Factory#1962)."
)

try:
    import merge.merge_policy as mp
except ImportError as _e:
    print(f"FATAL: cannot import merge.merge_policy: {_e}")  # noqa: T201
    sys.exit(2)
try:
    import review_tier
except ImportError as _e:
    print(f"FATAL: cannot import review_tier: {_e}")  # noqa: T201
    sys.exit(2)
try:
    import server.services.pr_endgame as pe
except ImportError as _e:
    print(f"FATAL: cannot import server.services.pr_endgame: {_e}")  # noqa: T201
    sys.exit(2)

# The exact inputs this generator probes. decide_merge gaining a parameter
# must fail loudly, not silently leave the matrix under-probed.
_PROBED_PARAMS = frozenset(
    {
        "tier",
        "host_ci_green",
        "tfactory_verdict",
        "achieved_val",
        "val_floor",
        "ci_parity",
        "deployment",
        "satisfied_gates",
    }
)

_REQUIRED_GATES = ("human-approval", "security-scan")
_RISK_CLASSES = ("high", "medium", "low", "")
_PROD_CLASSES = ("production", "staging", "dev", "")
_SAFE_PATH = "README.md"  # matches no high-risk pattern

_VAL_PROBES: tuple[tuple[object, object], ...] = (
    (2, None),
    (2, ""),
    (2, "VAL-three"),
    (1, 2),
    (2, 2),
    (3, 2),
    (None, 2),
    ("VAL-2 (3 lanes)", 2),
)


def _check_signature() -> None:
    params = set(inspect.signature(mp.decide_merge).parameters)
    if params != _PROBED_PARAMS:
        extra = ", ".join(sorted(params - _PROBED_PARAMS)) or "(none)"
        missing = ", ".join(sorted(_PROBED_PARAMS - params)) or "(none)"
        print(  # noqa: T201
            f"decide_merge gained parameter {extra} (missing: {missing}); "
            "extend the probe set"
        )
        sys.exit(3)


def _tf(b: bool) -> str:
    return "T" if b else "F"


def _table(
    tabs: list[dict[str, object]], header: list[str], rows: list[list[str]]
) -> list[str]:
    tabs.append({"header": header, "rows": rows})
    out = [
        "| " + " | ".join(header) + " |",
        "|" + "|".join("---" for _ in header) + "|",
    ]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return out


def _section_tiers(tabs: list[dict[str, object]]) -> tuple[list[str], int]:
    combos = list(
        itertools.product(
            (True, False), ("pass", "fail"), ((2, 1), (1, 2)), (True, False)
        )
    )
    rows: list[list[str]] = []
    for tier in sorted({*mp._TIER_ALIASES, "", "bogus"}):
        by_result: dict[str, list[str]] = {}
        for ci, verdict, (val, floor), parity in combos:
            result = mp.decide_merge(
                tier,
                host_ci_green=ci,
                tfactory_verdict=verdict,
                achieved_val=val,
                val_floor=floor,
                ci_parity=parity,
                deployment=None,
            )
            by_result.setdefault(result, []).append(
                f"ci={_tf(ci)} verdict={verdict} val={val}/{floor} parity={_tf(parity)}"
            )
        every = {c for conds in by_result.values() for c in conds}
        widest = max(sorted(by_result), key=lambda r: len(by_result[r]))
        for result in sorted(by_result):
            conds = by_result[result]
            others = {c for r, cs in by_result.items() if r != result for c in cs}
            if len(conds) == len(combos):
                cell = "always"
            elif result == widest and set(conds) == every - others and others:
                cell = "otherwise"
            else:
                cell = "; ".join(conds)
            rows.append([f"`{tier}`" if tier else "`(blank)`", f"`{result}`", cell])
    lines = [
        "## A1. Tier decision (no deployment block)",
        "",
        "ci = host CI green; verdict = TFactory verdict; val = achieved/floor VAL; "
        "parity = CI parity (T = true, F = false).",
        "",
    ]
    lines += _table(tabs, ["tier", "result", "when"], rows)
    return lines, len(rows)


def _section_overlay(tabs: list[dict[str, object]]) -> tuple[list[str], int]:
    seen: dict[tuple[tuple[str, ...], str], list[str]] = {}
    gate_sets: tuple[list[str], ...] = (
        [],
        [_REQUIRED_GATES[1]],
        list(_REQUIRED_GATES),
    )
    for risk, prod, sat in itertools.product(_RISK_CLASSES, _PROD_CLASSES, gate_sets):
        dep = {
            "risk_class": risk,
            "production_classification": prod,
            "system_gates": list(_REQUIRED_GATES),
        }
        reasons = tuple(mp.deployment_block_reasons(dep, satisfied_gates=sat))
        result = mp.decide_merge(
            "low",
            host_ci_green=True,
            tfactory_verdict="pass",
            achieved_val=2,
            val_floor=1,
            ci_parity=True,
            deployment=dep,
            satisfied_gates=sat,
        )
        seen.setdefault((reasons, result), []).append(
            f"risk={risk or '-'} prod={prod or '-'} satisfied={','.join(sat) or '-'}"
        )
    rows = [
        [
            "<br/>".join(r) if r else "(none)",
            f"`{result}`",
            f"{len(ex)} combos, e.g. {ex[0]}",
        ]
        for (r, result), ex in sorted(seen.items())
    ]
    lines = [
        "## A2. Deployment overlay (applied before the tier; all-green `low` change)",
        "",
        "Required gates: " + ", ".join(f"`{g}`" for g in _REQUIRED_GATES) + ".",
        "",
    ]
    lines += _table(tabs, ["block reasons", "result", "inputs"], rows)
    return lines, len(rows)


def _section_val(tabs: list[dict[str, object]]) -> tuple[list[str], int]:
    rows = [
        [f"`{a!r}`", f"`{f!r}`", str(mp._val_meets_floor(a, f))] for a, f in _VAL_PROBES
    ]
    lines = ["## A3. VAL floor semantics", ""]
    lines += _table(tabs, ["achieved", "floor", "meets floor"], rows)
    return lines, len(rows)


def _section_paths(tabs: list[dict[str, object]]) -> tuple[list[str], int]:
    patterns = review_tier.HIGH_RISK_PATTERNS
    probes = [*patterns, _SAFE_PATH]
    rows = [[f"`{p}`", f"`{mp.floor_from_paths([p])}`"] for p in probes]
    rows.append(["(no changed files)", f"`{mp.floor_from_paths([])}`"])
    lines = [
        "## A4. Path floor",
        "",
        "High-risk patterns: " + ", ".join(f"`{p}`" for p in patterns),
        "",
    ]
    lines += _table(tabs, ["changed path", "floor"], rows)
    return lines, len(rows)


# ponytail: pr_endgame has no constant for this name (is_auto_merge_enabled
# inlines the literal), so it is restated here; the flag call below still reads
# the live code, so a rename makes the "set" row go False rather than lie.
_AUTO_MERGE_ENV = "AIFACTORY_AUTO_MERGE"

# (control id, label, env var, reader). Shared by Section B3 and the control ids.
_FLAGS = (
    ("wiring.auto_merge_flag", "auto-merge", _AUTO_MERGE_ENV, pe.is_auto_merge_enabled),
    (
        "wiring.path_floor_flag",
        "path-floor enforcement",
        pe.PATH_RISK_FLOOR_ENV,
        pe.path_floor_enforced,
    ),
)

_GREEN_META = {
    "tfactoryVerdict": "pass",
    "achievedVal": 2,
    "valFloor": 1,
    "ciParity": True,
    "hostCiGreen": True,
}


# The matrix documents legacy tasks (no signed record) on an isolated host, so
# the numbers do not depend on the machine that regenerates them (#1667, D4-i).
# kubejob counts as isolated only with the durable store (#1667); the URL is
# read, never connected to.
_ISOLATED_HOST = {
    "AIFACTORY_BUILD_BACKEND": "kubejob",
    "DATABASE_URL": "postgresql+asyncpg://isolated-host/matrix",
}


@contextlib.contextmanager
def _env(**values: str | None) -> Iterator[None]:
    """Set (or, for None, remove) env vars; restore the originals on exit."""
    saved = {k: os.environ.get(k) for k in values}
    try:
        for k, v in values.items():
            if v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = v
        yield
    finally:
        for k, v in saved.items():
            if v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = v


@contextlib.contextmanager
def _differ_returns(wc: ModuleType, paths: list[str]) -> Iterator[None]:
    """Make the endgame's diff reader report *paths*; always restore it."""
    attr = "_get_changed_files_from_git"
    orig = getattr(wc, attr)
    try:
        setattr(wc, attr, lambda *_a, **_k: paths)
        yield
    finally:
        setattr(wc, attr, orig)


def _path_floor_rows(wc: ModuleType, root: Path, probe: str) -> list[list[str]]:
    """apply_path_risk_floor on a `low` task touching *probe*, advisory vs enforced."""
    rows: list[list[str]] = []
    with _differ_returns(wc, [probe]):
        for label, val in (("advisory (unset)", None), ("enforced (`1`)", "1")):
            spec = root / f"spec-{len(rows)}"
            spec.mkdir()
            with _env(**{pe.PATH_RISK_FLOOR_ENV: val}):
                eff, floor = pe.apply_path_risk_floor(
                    root, spec, "probe", "dev", "low", trusted=None
                )
            rows.append([label, f"`{eff!r}`", f"`{floor!r}`"])
    return rows


# DECLARED, not derived: the tracking issue for the finding the next table shows.
_LIVE_OVERLAY_ISSUE = "AIFactory#1658"


def _live_overlay_rows(wc: ModuleType, root: Path) -> list[list[str]]:
    """The RFC-0013 overlay through apply_path_risk_floor + merge_disposition.

    The diff is a non-risky path, so only the deployment overlay can raise the
    floor. Each row is deployment | enforce | effective tier | floor | disposition.
    """
    probes = (
        {"production_classification": _PROD_CLASSES[0]},
        {"risk_class": _RISK_CLASSES[0]},
        # A contract must not clear its own gate (#1663).
        {"system_gates": ["human-approval"], "satisfied_gates": ["human-approval"]},
    )
    rows: list[list[str]] = []
    with _differ_returns(wc, [_SAFE_PATH]):
        for dep in probes:
            for val in (None, "1"):
                spec = root / f"live-{len(rows)}"
                (spec / "context").mkdir(parents=True)
                contract = {"contract_version": "1", "deployment": dep}
                (spec / "context" / "task_contract.json").write_text(
                    json.dumps(contract)
                )
                (spec / "task_metadata.json").write_text(json.dumps(_GREEN_META))
                with _env(**{pe.PATH_RISK_FLOOR_ENV: val}, **_ISOLATED_HOST):
                    eff, floor = pe.apply_path_risk_floor(
                        spec, spec, "probe", "dev", "low", trusted=None
                    )
                    disposition = pe.merge_disposition(spec, eff, trusted=None)
                rows.append(
                    [
                        ", ".join(f"{k}={v}" for k, v in dep.items()),
                        "unset" if val is None else f"`{val}`",
                        f"`{eff!r}`",
                        f"`{floor!r}`",
                        f"`{disposition}`",
                    ]
                )
    return rows


def _live_overlay_lines(
    tabs: list[dict[str, object]], wc: ModuleType, root: Path
) -> tuple[list[str], int]:
    rows = _live_overlay_rows(wc, root)
    lines = [
        "### B5. Deployment overlay on the live path (`low` task, non-risky diff)",
        "",
    ]
    lines += _table(
        tabs,
        ["deployment", "enforce", "effective tier", "floor", "live disposition"],
        rows,
    )
    if any(r[1] == "unset" and r[4] == f"`{mp.AUTO_MERGE}`" for r in rows):
        lines += [
            "",
            "The RFC-0013 overlay is advisory on the live path unless "
            f"`{pe.PATH_RISK_FLOOR_ENV}` is set (see {_LIVE_OVERLAY_ISSUE}).",
        ]
    return lines, len(rows)


def _section_wiring(tabs: list[dict[str, object]]) -> tuple[list[str], int]:
    from cli import workspace_commands as wc  # noqa: PLC0415

    lines = ["## B. Live wiring (pr_endgame)", ""]
    n = 0
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        # Blank vs low
        green = root / "green"
        green.mkdir()
        (green / "task_metadata.json").write_text(json.dumps(_GREEN_META))
        with _env(**_ISOLATED_HOST):
            disp = {
                t: pe.merge_disposition(green, t, trusted=None)
                for t in (None, "", "low")
            }
        same = disp[None] == disp[""] == disp["low"]
        lines += ["### B1. Blank tier vs `low` (all-green signals)", ""]
        lines += _table(
            tabs,
            ["reviewTier", "disposition"],
            [[f"`{t!r}`", f"`{d}`"] for t, d in disp.items()],
        )
        lines += [""]
        lines += _table(tabs, ["check", "result"], [["blank == low", f"**{same}**"]])
        lines += [""]
        n += len(disp)

        # Unmeasured defaults
        empty = root / "empty"
        empty.mkdir()
        sig = pe.merge_gate_signals(empty)
        lines += ["### B2. Signals when nothing was measured", ""]
        lines += _table(
            tabs,
            ["signal", "default"],
            [[f"`{k}`", f"`{sig[k]!r}`"] for k in sorted(sig)],
        )
        lines += [""]
        n += len(sig)

        # Flag defaults
        rows = []
        for _cid, label, env, fn in sorted(_FLAGS, key=lambda f: f[1]):
            with _env(**{env: None}):
                unset = fn(None)
            with _env(**{env: "1"}):
                on = fn(None)
            rows.append([label, f"`{env}`", str(unset), str(on)])
        lines += ["### B3. Flags", ""]
        lines += _table(tabs, ["flag", "env var", "unset", 'set to "1"'], rows)
        lines += [""]
        n += len(rows)

        probe = review_tier.HIGH_RISK_PATTERNS[0]
        rows = _path_floor_rows(wc, root, probe)
        lines += [
            "### B4. Path floor on a `low` task touching "
            f"`{probe}`: (effective tier, floor)",
            "",
        ]
        lines += _table(tabs, ["enforcement", "effective tier", "floor"], rows)
        live, live_n = _live_overlay_lines(tabs, wc, root)
        lines += ["", *live]
        n += live_n
        lines += [
            "",
            "Defaults shown; per-project settings and per-deployment env override them.",
        ]
        n += len(rows)
    return lines, n


# ---- Section C: gate determinism (ast import closure) ----------------------
_ROOTS = (_REPO_ROOT / "apps" / "backend", _REPO_ROOT / "apps" / "web-server")

# Importing any of these (or a submodule) makes a gate model-assisted.
_MODEL_CLIENTS = (
    "anthropic",
    "openai",
    "claude_agent_sdk",
    "google.genai",
    "ollama",
    "core.client",
    "core.simple_client",
    "providers",
)

_ENTRY_POINTS = (
    "merge.merge_policy",
    "server.services.pr_review_service",
    "server.services.pr_endgame",
)

# Minimum resolved local modules per entry point: floor(0.5 * measured).
# max(2, floor(0.5 * measured)); measured 2026-10-07: merge_policy 2,
# pr_review_service 263 (incl. runner via spawn edge), pr_endgame 352. A walk
# under its minimum means the prober is broken, and it must never emit a label.
_MIN_CLOSURE: dict[str, int] = {
    "merge.merge_policy": 2,
    "server.services.pr_review_service": 131,
    "server.services.pr_endgame": 176,
}

# DECLARED spawn edge, verified against the caller's source below.
# pr_review_service runs the reviewer as a subprocess, so its model client is
# invisible to a static import walk. extra_roots mirror the PYTHONPATH the
# service sets (backend + runners/github), so the runner's bare imports resolve.
_SPAWN_EDGES: dict[str, dict[str, object]] = {
    "server.services.pr_review_service": {
        "script": "apps/backend/runners/github/runner.py",
        "extra_roots": ["apps/backend/runners/github"],
    },
}

# DECLARED, not derived - cross-repo (PFactory / TFactory are not probed here).
_DECLARED_GATES = (
    ("PFactory", "plan/review/gates.py::run_gates"),
    ("TFactory", "apps/backend/agents/evaluator.py::_run_evaluator_session"),
)


def _find(name: str, roots: tuple[Path, ...] = _ROOTS) -> tuple[Path, bool] | None:
    """Resolve a dotted module name to (file, is_package) under *roots*."""
    rel = Path(*name.split("."))
    for root in roots:
        if (root / rel / "__init__.py").is_file():
            return root / rel / "__init__.py", True
        if (root / rel).with_suffix(".py").is_file():
            return (root / rel).with_suffix(".py"), False
    return None


def _dynamic_imports(tree: ast.AST) -> list[int]:
    """Line numbers of importlib.import_module / __import__ calls."""
    return [
        n.lineno
        for n in ast.walk(tree)
        if isinstance(n, ast.Call)
        and (
            (
                isinstance(n.func, ast.Name)
                and n.func.id in {"__import__", "import_module"}
            )
            or (isinstance(n.func, ast.Attribute) and n.func.attr == "import_module")
        )
    ]


@functools.cache
def _closure(
    module_name: str, roots: tuple[Path, ...] = _ROOTS
) -> tuple[frozenset[str], frozenset[str], tuple[str, ...]]:
    """(local modules walked, every imported name, dynamic-import sites).

    Results are cached and immutable; callers must not mutate them.
    """
    local: set[str] = set()
    names: set[str] = set()
    dynamic: list[str] = []
    queue = [module_name]
    while queue:
        mod = queue.pop()
        if mod in local:
            continue
        found = _find(mod, roots)
        if found is None:
            continue
        path, is_pkg = found
        local.add(mod)
        pkg = mod if is_pkg else mod.rpartition(".")[0]
        tree = ast.parse(path.read_text(encoding="utf-8"))
        dynamic += [f"{mod}:{ln}" for ln in _dynamic_imports(tree)]
        for node in ast.walk(tree):
            if isinstance(node, ast.Import):
                found_names = [a.name for a in node.names]
            elif isinstance(node, ast.ImportFrom):
                base = node.module or ""
                if node.level:
                    parts = pkg.split(".") if pkg else []
                    parts = parts[: len(parts) - (node.level - 1)]
                    base = ".".join([*parts, *([base] if base else [])])
                found_names = [base, *(f"{base}.{a.name}" for a in node.names)]
            else:
                continue
            for n in found_names:
                if not n:
                    continue
                names.add(n)
                if _find(n, roots):
                    queue.append(n)
    return frozenset(local), frozenset(names), tuple(sorted(dynamic))


def _simple_stmts(tree: ast.AST) -> list[ast.stmt]:
    """Statements with no nested body (so 'one statement' means one statement)."""
    compound = ("body", "orelse", "handlers", "finalbody")
    return [
        n
        for n in ast.walk(tree)
        if isinstance(n, ast.stmt) and not any(hasattr(n, a) for a in compound)
    ]


def _strings(node: ast.AST) -> set[str]:
    return {
        n.value
        for n in ast.walk(node)
        if isinstance(n, ast.Constant) and isinstance(n.value, str)
    }


def _assigned(stmt: ast.stmt) -> set[str]:
    targets = (
        stmt.targets
        if isinstance(stmt, ast.Assign)
        else [stmt.target]
        if isinstance(stmt, ast.AnnAssign)
        else []
    )
    return {t.id for t in targets if isinstance(t, ast.Name)}


def _name_ids(node: ast.AST) -> set[str]:
    return {n.id for n in ast.walk(node) if isinstance(n, ast.Name)}


def _verify_spawn_edge(
    caller: Path, edge: dict[str, object], repo: Path = _REPO_ROOT
) -> None:
    """Raise ValueError unless *caller*'s source still spawns the declared script.

    The script path constants must sit in ONE statement that assigns a variable,
    and a spawn call must reference that variable (directly, or via a list built
    from it). Each extra root's last two path parts must likewise appear in one
    statement (the PYTHONPATH build).
    """
    stale = ValueError("spawn edge no longer matches its source - update _SPAWN_EDGES")
    tree = ast.parse(caller.read_text(encoding="utf-8"))
    stmts = _simple_stmts(tree)
    if not (repo / str(edge["script"])).is_file():
        raise stale
    script_parts = set(Path(str(edge["script"])).parts[-3:])
    script_vars: set[str] = set()
    for st in stmts:
        if script_parts <= _strings(st):
            script_vars |= _assigned(st)
    for root in edge["extra_roots"]:  # type: ignore[attr-defined]
        if not any(set(Path(str(root)).parts[-2:]) <= _strings(st) for st in stmts):
            raise stale
    for call in (n for n in ast.walk(tree) if isinstance(n, ast.Call)):
        f = call.func
        if not isinstance(f, ast.Attribute) or not (
            f.attr == "create_subprocess_exec"
            or (isinstance(f.value, ast.Name) and f.value.id == "subprocess")
        ):
            continue
        used = set().union(*(_name_ids(a) for a in call.args)) if call.args else set()
        via = {
            v
            for st in stmts
            for v in _assigned(st)
            if v in used and _name_ids(st) & script_vars
        }
        if used & script_vars or via:
            return
    raise stale


def _parent_reach(
    local: frozenset[str], roots: tuple[Path, ...]
) -> dict[str, list[str]]:
    """Parent package __init__s of the closure that reach a pinned model client."""
    parents = {
        ".".join(m.split(".")[:i]) for m in local for i in range(1, len(m.split(".")))
    }
    out: dict[str, list[str]] = {}
    for parent in sorted(parents):
        found = _find(parent, roots)
        if found is None:
            continue
        hit = _hits(_closure(parent, roots)[1])
        if hit:
            f = found[0]
            out[
                str(f.relative_to(_REPO_ROOT) if f.is_relative_to(_REPO_ROOT) else f)
            ] = hit
    return out


def _entry_closure(
    entry: str,
) -> tuple[frozenset[str], frozenset[str], str, tuple[str, ...], dict[str, list[str]]]:
    """(local modules, names, spawn label, dynamic imports, parent-__init__ reach)."""
    local, names, dynamic = _closure(entry)
    reach = _parent_reach(local, _ROOTS)
    edge = _SPAWN_EDGES.get(entry)
    if edge is None:
        return local, names, "-", dynamic, reach
    found = _find(entry)
    try:
        if found is None:
            raise ValueError("caller not found")
        _verify_spawn_edge(found[0], edge)
    except ValueError as e:
        print(  # noqa: T201
            f"spawn edge for {entry} no longer matches its source - "
            f"update _SPAWN_EDGES ({e})"
        )
        sys.exit(4)
    script = _REPO_ROOT / str(edge["script"])
    roots = (*_ROOTS, *(_REPO_ROOT / str(r) for r in edge["extra_roots"]))  # type: ignore[attr-defined]
    mod = ".".join(script.relative_to(_ROOTS[0]).with_suffix("").parts)
    sub_local, sub_names, sub_dyn = _closure(mod, roots)
    reach = {**reach, **_parent_reach(sub_local, roots)}
    return (
        local | sub_local,
        names | sub_names,
        f"`{script.relative_to(_REPO_ROOT / 'apps/backend')}`",
        tuple(sorted({*dynamic, *sub_dyn})),
        dict(sorted(reach.items())),
    )


def _hits(names: Collection[str]) -> list[str]:
    return sorted(
        c for c in _MODEL_CLIENTS if any(n == c or n.startswith(c + ".") for n in names)
    )


def _label(names: Collection[str], dynamic: tuple[str, ...] = ()) -> str:
    """model-assisted / undetermined / deterministic for the gate's own imports."""
    dyn = ""
    if dynamic:
        more = f" (+{len(dynamic) - 1} more)" if len(dynamic) > 1 else ""
        dyn = f"dynamic import: {dynamic[0]}{more}"
    if _hits(names):
        return f"model-assisted ({dyn})" if dyn else "model-assisted"
    return f"undetermined ({dyn})" if dyn else "deterministic"


def _section_gates(tabs: list[dict[str, object]]) -> tuple[list[str], int]:
    rows = []
    meta: list[dict[str, object]] = []
    for entry in _ENTRY_POINTS:
        local, names, via, dynamic, reach = _entry_closure(entry)
        if len(local) < _MIN_CLOSURE[entry]:
            print(  # noqa: T201
                f"prober resolved {len(local)} modules for {entry} "
                f"(min {_MIN_CLOSURE[entry]}) - refusing to label"
            )
            sys.exit(4)
        hit = _hits(names)
        init_hits = sorted({h for hs in reach.values() for h in hs})
        where = (
            ", ".join(f"`{p}`" for p in reach)
            if len(reach) <= _MAX_INLINE_INITS
            else "see JSON `gates[].init_reach`"
        )
        init_cell = (
            f"yes ({len(reach)}): {where}; reaches "
            + ", ".join(f"`{h}`" for h in init_hits)
            if reach
            else "no"
        )
        meta.append({"entry": entry, "init_reach": sorted(reach)})
        rows.append(
            [
                f"`{entry}`",
                _label(names, dynamic),
                ", ".join(f"`{h}`" for h in hit) or "-",
                init_cell,
                str(len(local)),
                via,
            ]
        )
    lines = [
        "## C. Gate determinism (static import closure)",
        "",
        "label = the gate module's own transitive imports; package `__init__` side "
        "effects are reported separately in the next column.",
        "",
    ]
    lines += _table(
        tabs,
        [
            "gate",
            "label",
            "model clients imported",
            "package __init__ reaches a model client",
            "local modules",
            "via spawn",
        ],
        rows,
    )
    tabs[0]["gates"] = meta  # lifted to the top level of the JSON by build()
    lines += ["", "Declared, unverified (cross-repo, not probed):", ""]
    lines += _table(tabs, ["repo", "gate"], [[r, f"`{g}`"] for r, g in _DECLARED_GATES])
    lines += [
        "",
        "`pr_endgame`'s review verdict is injected, not computed there; the review "
        "component is the separate `pr_review_service` row.",
    ]
    return lines, len(rows)


# ---- Section D: control objectives joined from TOML ------------------------
_CONTROLS_TOML = _REPO_ROOT / "docs" / "compliance" / "control-objectives.toml"
_CONTROL_KEYS = {"objective", "evidence", "frameworks", "claim"}


class ControlsError(Exception):
    """The control-objectives file is malformed or disagrees with the code."""


def _derived_ids() -> list[str]:
    """Control ids for what Sections A-C render."""
    ids = [f"policy.tier.{b}" for b in sorted(set(mp._TIER_ALIASES.values()))]
    ids += ["policy.overlay", "policy.val_floor", "policy.path_floor"]
    ids += ["wiring.blank_tier", "wiring.live_overlay", *(f[0] for f in _FLAGS)]
    ids += [f"gate.{e}" for e in _ENTRY_POINTS]
    return sorted(ids)


def _load_controls(path: Path) -> dict[str, dict[str, object]]:
    """Read and validate the TOML, then join it against the derived ids."""
    try:
        data = tomllib.loads(path.read_text(encoding="utf-8"))
    except (OSError, tomllib.TOMLDecodeError) as e:
        raise ControlsError(f"cannot read {path}: {e}") from e
    raw = data.get("controls", {})
    if not isinstance(raw, dict):
        raise ControlsError(f"`controls` is not a table in {path.name}")
    controls: dict[str, dict[str, object]] = {}
    for cid, c in sorted(raw.items()):
        if not isinstance(c, dict):
            raise ControlsError(f"control {cid!r} is malformed in {path.name}")
        controls[cid] = c
    for cid, c in sorted(controls.items()):
        fw = c.get("frameworks")
        if (
            not set(c) <= _CONTROL_KEYS
            or not isinstance(c.get("claim", ""), str)
            or not isinstance(c.get("objective"), str)
            or not isinstance(c.get("evidence"), str)
            or not isinstance(fw, list)
            or not all(isinstance(x, str) for x in fw)
        ):
            raise ControlsError(f"control {cid!r} is malformed in {path.name}")
    derived = set(_derived_ids())
    problems = [
        f"orphan control (no derived id): {cid}"
        for cid in sorted(set(controls) - derived)
    ]
    problems += [
        f"derived control has no entry: {cid}"
        for cid in sorted(derived - set(controls))
    ]
    if problems:
        raise ControlsError("\n".join(problems))
    return controls


def _section_controls(
    tabs: list[dict[str, object]], controls: dict[str, dict[str, object]]
) -> tuple[list[str], int]:
    rows = [
        [
            f"`{cid}`",
            str(c["objective"]),
            "; ".join(cast("list[str]", c["frameworks"])),
            f"`{c['evidence']}`",
            str(c.get("claim", "-")),
        ]
        for cid, c in sorted(controls.items())
    ]
    lines = ["## D. Control objectives", ""]
    lines += _table(
        tabs, ["control", "objective", "frameworks", "evidence", "claim"], rows
    )
    return lines, len(rows)


_SECTIONS = (
    ("tiers", _section_tiers),
    ("overlay", _section_overlay),
    ("val", _section_val),
    ("paths", _section_paths),
    ("wiring", _section_wiring),
    ("gates", _section_gates),
)

_OUT_MD = _REPO_ROOT / "docs" / "docs" / "compliance" / "autonomy-matrix.md"
_OUT_JSON = _REPO_ROOT / "docs" / "static" / "compliance" / "autonomy-matrix.json"
_FRONT_MATTER = (
    "---\ntitle: Autonomy matrix (generated)\n---\n\n"
    f"{{/*\n{_GENERATED_BANNER}\n*/}}\n\n"
)
# Row-count floors asserted by --check before the byte comparison.
_MIN_TIER_ROWS, _MIN_OVERLAY_ROWS, _VAL_ROWS, _GATE_ROWS = 8, 12, 8, 3
_MAX_INLINE_INITS = 3


def build(
    controls_path: Path = _CONTROLS_TOML,
) -> tuple[str, str, dict[str, int]]:
    """Return (markdown, json text, row counts)."""
    _check_signature()
    controls = _load_controls(controls_path)
    out = ["# Autonomy matrix (generated)", ""]
    sections: list[dict[str, object]] = []
    gates: object = []
    counts: dict[str, int] = {}
    steps = [
        *_SECTIONS,
        ("controls", lambda tabs: _section_controls(tabs, controls)),
    ]
    for key, fn in steps:
        tabs: list[dict[str, object]] = []
        lines, counts[key] = fn(tabs)
        out += [*lines, ""]
        if key == "gates":
            gates = tabs[0].pop("gates")
        sections.append({"id": key, "title": lines[0].lstrip("# "), "tables": tabs})
    md = _FRONT_MATTER + "\n".join(out)
    doc = {"controls": controls, "gates": gates, "sections": sections}
    return md, json.dumps(doc, indent=2, sort_keys=True) + "\n", counts


def render() -> str:
    return build()[0]


def _first_diff(name: str, want: str, have: str) -> str:
    w, h = want.splitlines(), have.splitlines()
    for i in range(max(len(w), len(h))):
        a = w[i] if i < len(w) else "<eof>"
        b = h[i] if i < len(h) else "<eof>"
        if a != b:
            return (
                f"{name}: line {i + 1} differs\n"
                f"  generated: {a[:200]}\n  committed: {b[:200]}"
            )
    return f"{name}: differs"


def check(
    md_path: Path = _OUT_MD,
    json_path: Path = _OUT_JSON,
    controls_path: Path = _CONTROLS_TOML,
) -> int:
    try:
        md, js, c = build(controls_path)
    except ControlsError as e:
        print(e)  # noqa: T201
        return 1
    floors = {
        "tiers": (c["tiers"] >= _MIN_TIER_ROWS),
        "overlay": (c["overlay"] >= _MIN_OVERLAY_ROWS),
        "val": (c["val"] == _VAL_ROWS),
        "paths": (c["paths"] >= len(review_tier.HIGH_RISK_PATTERNS) + 2),
        "gates": (c["gates"] == _GATE_ROWS),
        "controls": (c["controls"] == len(_derived_ids())),
    }
    bad = [k for k, ok in floors.items() if not ok]
    if bad:
        print(f"row-count minimum violated: {', '.join(bad)} ({c})")  # noqa: T201
        return 1
    for path, want in ((md_path, md), (json_path, js)):
        have = path.read_text(encoding="utf-8") if path.is_file() else ""
        if have != want:
            print(_first_diff(str(path), want, have))  # noqa: T201
            return 1
    print(  # noqa: T201
        f"ok: tiers={c['tiers']} overlay={c['overlay']} val={c['val']} "
        f"paths={c['paths']} gates={c['gates']} controls={c['controls']}"
    )
    return 0


def main(
    argv: list[str] | None = None,
    *,
    md_path: Path = _OUT_MD,
    json_path: Path = _OUT_JSON,
    controls_path: Path = _CONTROLS_TOML,
) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stdout", action="store_true", help="Print the markdown.")
    parser.add_argument(
        "--check", action="store_true", help="Fail if outputs are stale."
    )
    args = parser.parse_args(argv)
    if args.check:
        return check(md_path, json_path, controls_path)
    try:
        md, js, _ = build(controls_path)
    except ControlsError as e:
        print(e)  # noqa: T201
        return 1
    if args.stdout:
        sys.stdout.write(md)
        return 0
    for path, text in ((md_path, md), (json_path, js)):
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text, encoding="utf-8")
        print(f"wrote {path}")  # noqa: T201
    return 0


if __name__ == "__main__":
    sys.exit(main())
