#!/usr/bin/env python3
"""Generate the autonomy matrix from the live merge policy (Factory#1962).

Every row is produced by CALLING ``merge.merge_policy`` / ``review_tier``;
nothing is transcribed, so the page cannot drift from the code.

Usage:
    python scripts/gen_autonomy_matrix.py --stdout   # print the markdown
"""

from __future__ import annotations

import argparse
import contextlib
import inspect
import itertools
import json
import os
import sys
import tempfile
from collections.abc import Iterator
from pathlib import Path

_REPO_ROOT = Path(__file__).resolve().parents[1]
for _p in (_REPO_ROOT / "apps" / "backend", _REPO_ROOT / "apps" / "web-server"):
    sys.path.insert(0, str(_p))

_GENERATED_BANNER = (
    "GENERATED by scripts/gen_autonomy_matrix.py from merge.merge_policy.\n"
    "DO NOT EDIT BY HAND - rerun the generator (Factory#1962)."
)

try:
    import merge.merge_policy as mp
except ImportError as _e:
    print(f"FATAL: cannot import merge.merge_policy: {_e}")  # noqa: T201
    sys.exit(2)
try:
    import review_tier
except ImportError as _e:
    print(f"FATAL: cannot import review_tier: {_e}")  # noqa: T201
    sys.exit(2)
try:
    import server.services.pr_endgame as pe
except ImportError as _e:
    print(f"FATAL: cannot import server.services.pr_endgame: {_e}")  # noqa: T201
    sys.exit(2)

# The exact inputs this generator probes. decide_merge gaining a parameter
# must fail loudly, not silently leave the matrix under-probed.
_PROBED_PARAMS = frozenset(
    {
        "tier",
        "host_ci_green",
        "tfactory_verdict",
        "achieved_val",
        "val_floor",
        "ci_parity",
        "deployment",
        "satisfied_gates",
    }
)

_VAL_PROBES: tuple[tuple[object, object], ...] = (
    (2, None),
    (2, ""),
    (2, "VAL-three"),
    (1, 2),
    (2, 2),
    (3, 2),
    (None, 2),
    ("VAL-2 (3 lanes)", 2),
)


def _check_signature() -> None:
    params = set(inspect.signature(mp.decide_merge).parameters)
    if params != _PROBED_PARAMS:
        extra = ", ".join(sorted(params - _PROBED_PARAMS)) or "(none)"
        missing = ", ".join(sorted(_PROBED_PARAMS - params)) or "(none)"
        print(  # noqa: T201
            f"decide_merge gained parameter {extra} (missing: {missing}); "
            "extend the probe set"
        )
        sys.exit(3)


def _tf(b: bool) -> str:
    return "T" if b else "F"


def _table(header: list[str], rows: list[list[str]]) -> list[str]:
    out = [
        "| " + " | ".join(header) + " |",
        "|" + "|".join("---" for _ in header) + "|",
    ]
    out += ["| " + " | ".join(r) + " |" for r in rows]
    return out


def _section_tiers() -> tuple[list[str], int]:
    combos = list(
        itertools.product(
            (True, False), ("pass", "fail"), ((2, 1), (1, 2)), (True, False)
        )
    )
    rows: list[list[str]] = []
    for tier in sorted({*mp._TIER_ALIASES, "", "bogus"}):
        by_result: dict[str, list[str]] = {}
        for ci, verdict, (val, floor), parity in combos:
            result = mp.decide_merge(
                tier,
                host_ci_green=ci,
                tfactory_verdict=verdict,
                achieved_val=val,
                val_floor=floor,
                ci_parity=parity,
                deployment=None,
            )
            by_result.setdefault(result, []).append(
                f"ci={_tf(ci)} verdict={verdict} val={val}/{floor} parity={_tf(parity)}"
            )
        for result in sorted(by_result):
            conds = by_result[result]
            cell = "always" if len(conds) == len(combos) else "; ".join(conds)
            rows.append([f"`{tier}`" if tier else "`(blank)`", f"`{result}`", cell])
    lines = ["## A1. Tier decision (no deployment block)", ""]
    lines += _table(["tier", "result", "when"], rows)
    return lines, len(rows)


def _section_overlay() -> tuple[list[str], int]:
    seen: dict[tuple[tuple[str, ...], str], list[str]] = {}
    gate_sets = ([], ["security-scan"], ["human-approval", "security-scan"])
    for risk, prod, sat in itertools.product(
        ("high", "medium", "low", ""), ("production", "staging", "dev", ""), gate_sets
    ):
        dep = {
            "risk_class": risk,
            "production_classification": prod,
            "system_gates": ["human-approval", "security-scan"],
        }
        reasons = tuple(mp.deployment_block_reasons(dep, satisfied_gates=sat))
        result = mp.decide_merge(
            "low",
            host_ci_green=True,
            tfactory_verdict="pass",
            achieved_val=2,
            val_floor=1,
            ci_parity=True,
            deployment=dep,
            satisfied_gates=sat,
        )
        seen.setdefault((reasons, result), []).append(
            f"risk={risk or '-'} prod={prod or '-'} satisfied={','.join(sat) or '-'}"
        )
    rows = [
        [
            "<br>".join(r) if r else "(none)",
            f"`{result}`",
            f"{len(ex)} combos, e.g. {ex[0]}",
        ]
        for (r, result), ex in sorted(seen.items())
    ]
    lines = [
        "## A2. Deployment overlay (applied before the tier; all-green `low` change)",
        "",
        "Required gates: `human-approval`, `security-scan`.",
        "",
    ]
    lines += _table(["block reasons", "result", "inputs"], rows)
    return lines, len(rows)


def _section_val() -> tuple[list[str], int]:
    rows = [
        [f"`{a!r}`", f"`{f!r}`", str(mp._val_meets_floor(a, f))] for a, f in _VAL_PROBES
    ]
    lines = ["## A3. VAL floor semantics", ""]
    lines += _table(["achieved", "floor", "meets floor"], rows)
    return lines, len(rows)


def _section_paths() -> tuple[list[str], int]:
    patterns = review_tier.HIGH_RISK_PATTERNS
    probes = [*patterns, "README.md"]
    rows = [[f"`{p}`", f"`{mp.floor_from_paths([p])}`"] for p in probes]
    rows.append(["(no changed files)", f"`{mp.floor_from_paths([])}`"])
    lines = [
        "## A4. Path floor",
        "",
        "High-risk patterns: " + ", ".join(f"`{p}`" for p in patterns),
        "",
    ]
    lines += _table(["changed path", "floor"], rows)
    return lines, len(rows)


# ponytail: pr_endgame has no constant for this name (is_auto_merge_enabled
# inlines the literal), so it is restated here; the flag call below still reads
# the live code, so a rename makes the "set" row go False rather than lie.
_AUTO_MERGE_ENV = "AIFACTORY_AUTO_MERGE"

_GREEN_META = {
    "tfactoryVerdict": "pass",
    "achievedVal": 2,
    "valFloor": 1,
    "ciParity": True,
    "hostCiGreen": True,
}


@contextlib.contextmanager
def _env(**values: str | None) -> Iterator[None]:
    """Set (or, for None, remove) env vars; restore the originals on exit."""
    saved = {k: os.environ.get(k) for k in values}
    try:
        for k, v in values.items():
            if v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = v
        yield
    finally:
        for k, v in saved.items():
            if v is None:
                os.environ.pop(k, None)
            else:
                os.environ[k] = v


def _section_wiring() -> tuple[list[str], int]:
    from cli import workspace_commands as wc  # noqa: PLC0415

    lines = ["## B. Live wiring (pr_endgame)", ""]
    n = 0
    with tempfile.TemporaryDirectory() as td:
        root = Path(td)
        # Blank vs low
        green = root / "green"
        green.mkdir()
        (green / "task_metadata.json").write_text(json.dumps(_GREEN_META))
        disp = {t: pe.merge_disposition(green, t) for t in (None, "", "low")}
        same = disp[None] == disp[""] == disp["low"]
        lines += ["### B1. Blank tier vs `low` (all-green signals)", ""]
        lines += _table(
            ["reviewTier", "disposition"],
            [[f"`{t!r}`", f"`{d}`"] for t, d in disp.items()],
        )
        lines += ["", f"blank == low: **{same}**", ""]
        n += len(disp)

        # Unmeasured defaults
        empty = root / "empty"
        empty.mkdir()
        sig = pe.merge_gate_signals(empty)
        lines += ["### B2. Signals when nothing was measured", ""]
        lines += _table(
            ["signal", "default"], [[f"`{k}`", f"`{sig[k]!r}`"] for k in sorted(sig)]
        )
        lines += [""]
        n += len(sig)

        # Flag defaults
        names = {
            "auto-merge": (_AUTO_MERGE_ENV, pe.is_auto_merge_enabled),
            "path-floor enforcement": (pe.PATH_RISK_FLOOR_ENV, pe.path_floor_enforced),
        }
        rows = []
        for label, (env, fn) in sorted(names.items()):
            with _env(**{env: None}):
                unset = fn(None)
            with _env(**{env: "1"}):
                on = fn(None)
            rows.append([label, f"`{env}`", str(unset), str(on)])
        lines += ["### B3. Flags", ""]
        lines += _table(["flag", "env var", "unset", 'set to "1"'], rows)
        lines += [""]
        n += len(rows)

        # Path floor, advisory vs enforced
        probe = review_tier.HIGH_RISK_PATTERNS[0]
        orig = wc._get_changed_files_from_git
        rows = []
        try:
            wc._get_changed_files_from_git = lambda *a, **k: [probe]
            for label, val in (("advisory (unset)", None), ("enforced (`1`)", "1")):
                spec = root / f"spec-{len(rows)}"
                spec.mkdir()
                with _env(**{pe.PATH_RISK_FLOOR_ENV: val}):
                    eff, floor = pe.apply_path_risk_floor(
                        root, spec, "probe", "dev", "low"
                    )
                rows.append([label, f"`{eff!r}`", f"`{floor!r}`"])
        finally:
            wc._get_changed_files_from_git = orig
        lines += [
            "### B4. Path floor on a `low` task touching "
            f"`{probe}`: (effective tier, floor)",
            "",
        ]
        lines += _table(["enforcement", "effective tier", "floor"], rows)
        lines += [
            "",
            "Defaults shown; per-project settings and per-deployment env override them.",
        ]
        n += len(rows)
    return lines, n


def render() -> str:
    _check_signature()
    out = [f"<!--\n{_GENERATED_BANNER}\n-->", "", "# Autonomy matrix (generated)", ""]
    for section in (
        _section_tiers,
        _section_overlay,
        _section_val,
        _section_paths,
        _section_wiring,
    ):
        lines, _n = section()
        out += lines + [""]
    return "\n".join(out)


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--stdout", action="store_true", help="Print the markdown.")
    args = parser.parse_args(argv)
    text = render()
    if args.stdout:
        sys.stdout.write(text)
    return 0


if __name__ == "__main__":
    sys.exit(main())
